# Generated by Django 5.1.1 on 2024-09-17 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term', models.PositiveIntegerField(help_text='Term in months')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Repayed', 'Repayed'), ('Defaulted', 'Defaulted')], default='Approved', max_length=20)),
                ('disbursed_date', models.DateField(blank=True, null=True)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('total_repayment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('penalty_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.user')),
                ('loan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loantype')),
            ],
        ),
    ]
