# Generated by Django 5.1.1 on 2024-09-17 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('score_date', models.DateField(default=django.utils.timezone.now)),
                ('adjustment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustment_date', models.DateField(blank=True, null=True)),
                ('adjustment_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_record', to='loans.user')),
            ],
        ),
    ]
